language: latex

services:
  - docker

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1dc333127f19ec0dce8d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
  - docker pull iandennismiller/pub2
  - docker ps -a

script:
  - docker run iandennismiller/pub2 /bin/sh -c "apt -y install aspell texlive-xetex latexmk; cd /opt; git clone https://github.com/iandennismiller/mueller-report.git; cd mueller-report; cd src; make all"
